name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - uses: mattnite/setup-gyro@v1
      
      - run: gyro fetch
      
      - run: zig build --build-file "build-all.zig"
      
      - run: rm zig-out/bin/installer-cli

      - name: Release
        uses: softprops/action-gh-release@v0.1.13
        with:
          name: ${{ github.sha }}
          tag_name: ${{ github.ref }}
          # Note-worthy description of changes in release
          body: ${{ join(github.event.commits.*.message, '\n') }}
          # Newline-delimited list of path globs for asset files to upload
          files: "zig-out/bin/*"
          # Fails if any of the `files` globs match nothing. Defaults to false
          fail_on_unmatched_files: true
          # Repository to make releases against, in <owner>/<repo> format
          repository: "kernel-mod/installer-cli"
