name: Build

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master

      - uses: mattnite/setup-gyro@v1
      
      - run: gyro build
      
      - run: zig build --build-file "build-all.zig"

      - name: Release
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@6034af24fba4e5a8e975aaa6056554efe4c794d0
        uses: softprops/action-gh-release@v0.1.13
        with:
          # Note-worthy description of changes in release
          body: ""
          # Newline-delimited list of path globs for asset files to upload
          files: "zig-out/bin/*"
          # Fails if any of the `files` globs match nothing. Defaults to false
          fail_on_unmatched_files: true
          # Repository to make releases against, in <owner>/<repo> format
          repository: "kernel-mod/installer-cli"
