name: Build

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master

      - uses: mattnite/setup-gyro@v1
      
      - run: gyro update
      
      - run: zig build --build-file "build-all.zig"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          # A file, directory or wildcard pattern that describes what to upload
          path: "zig-out/bin/*"
          if-no-files-found: "error"
          
#       - name: Release Drafter
#         # You may pin to the exact commit or the version.
#         # uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4
#         uses: release-drafter/release-drafter@v5.15.0
#         with:
#           publish: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
