name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string
      release_description_message:
        required: false
        type: string
        default: "A new release for Kernel's `installer-cli`."
      release_description_notes:
        required: false
        type: string
        default: "Nothing to note."

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.9.1

      - name: Setup Gyro
        uses: mattnite/setup-gyro@v1.1.0

      - name: Build Artifacts
        run: |
          gyro fetch
          zig build --build-file "build-all.zig"

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          name: installer-cli ${{ inputs.tag_name }}
          tag_name: ${{ inputs.tag_name }}
          # Note-worthy description of changes in release
          body: |-
            ${{ inputs.release_description_message }}

            ### Release Notes for ${{ inputs.tag_name }}

            ${{ inputs.release_description_notes }}

            > This release was created by `${{ github.event.actor }}`.
          # Newline-delimited list of path globs for asset files to upload
          files: "zig-out/bin/*"
          # Fails if any of the `files` globs match nothing. Defaults to false
          fail_on_unmatched_files: true
          # Repository to make releases against, in <owner>/<repo> format
          repository: "Sepruko/installer-cli"
